kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: codeigniter-api-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
#  storageClassName: openebs-hostpath