apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeigniter-api
  labels:
    app: codeigniter-api
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: codeigniter-api
  template:
    metadata:
      labels:
        app: codeigniter-api
    spec:
      containers:
        - name: codeigniter-api
          image: gmarconsidom/codeigiter-api:v0.3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - mountPath: /app/myapp/writable/session
              name: codeigniter-api-data
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_DATABASE
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: codeigniter-api-data
          persistentVolumeClaim:
            claimName: codeigniter-api-vol