apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeigniter-api 
  labels:
    app: codeigniter-api 
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: codeigniter-api
  template:
    metadata:
      labels: 
        app: codeigniter-api
    spec:
      containers:
      - name: codeigniter-api
        image: gmarconsidom/codeigiter-api:v0.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_DATABASE